### ISSUE TITLE
Multiple events with the same name.

### ISSUE THREAD

**Issue by FriedSock** [svenfuchs/simple_states#17]
Please correct me if I am wrong, but at the moment it is not possible to define multiple events with the same name. It would be good if you were allowed to do this, as long as there were not multiple events with the same name stemming from the same state. Ie. I would like to define:

     event :close, from: :created, to: :closed
     event :close, from: :open, to: :closed

But am having to define 

     event :close_created, from: :created, to: :closed
     event :close_open, from: :open, to: :closed

This could be implemented by defining event method names by concatenating their name and starting state. Would you accept a PR with this proposed method, or do you have any other opinions?

Thanks
Jack

**Comment by yoshdog** [comment]
:+1:

**Comment by svenfuchs** [comment]
I guess what you are after is a more full-blown state machine library, which isn't this one.

One thing you could do is

```
def close
  if was_created?
    # ...
  else
    # ...
  end
end
```
